CREATE SEQUENCE PAT_ERX_TRAN_RESP_ERR_SEQ  START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 20 NOCYCLE NOORDER;

CREATE TABLE HOSPITAL.PAT_ERX_TRAN_RESP_ERR
(
ID		NUMBER NOT NULL,
ENTITY_ID	NVARCHAR2(250),
AdditionalReference NVARCHAR2(255),
AdditionalReferenceObjectName NVARCHAR2(255),
Reference NVARCHAR2(255),
ReferenceObjectName NVARCHAR2(255),
PropertyName NVARCHAR2(255),
RuleCode NVARCHAR2(255),
ErrorText NVARCHAR2(1000),
ObjectName NVARCHAR2(255),
Transaction_Type NVARCHAR2(255)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PAT_ERX_TRAN_RESP_ERR_PK ON PAT_ERX_TRAN_RESP_ERR
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER PAT_ERX_TRAN_RESP_ERR 
BEFORE INSERT
ON PAT_ERX_TRAN_RESP_ERR 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT PAT_ERX_TRAN_RESP_ERR_SEQ.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;

ALTER TABLE PAT_ERX_TRAN_RESP_ERR ADD (
  CONSTRAINT PAT_ERX_TRAN_RESP_ERR_PK
 PRIMARY KEY
 (ID));
 