CREATE SEQUENCE RIAYATI_PENDING_REQUESTS_SEQ  START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 20 NOCYCLE NOORDER;

CREATE TABLE HOSPITAL.RIAYATI_PENDING_REQUESTS
(
ID		NUMBER NOT NULL,
FACILITY_ID NUMBER NOT NULL,
REQUEST_TYPE  NVARCHAR2(100),        
PAYLOAD       BLOB,
IS_PROCESSING  NUMBER DEFAULT 0,     
RESPONSE_STATUS_CODE NVARCHAR2(100),
ERROR_MESSAGE     NVARCHAR2(500),    
CREATED_DATE      DATE DEFAULT SYSDATE,    
RESPONSE		   BLOB
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX RIAYATI_PENDING_REQUESTS_PK ON RIAYATI_PENDING_REQUESTS
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER RIAYATI_PENDING_REQUESTS 
BEFORE INSERT
ON RIAYATI_PENDING_REQUESTS 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT RIAYATI_PENDING_REQUESTS_SEQ.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;

ALTER TABLE RIAYATI_PENDING_REQUESTS ADD (
  CONSTRAINT RIAYATI_PENDING_REQUESTS_PK
 PRIMARY KEY
 (ID));
 