CREATE SEQUENCE PAT_ERX_AUTHORIZATION_SEQ  START WITH 1 INCREMENT BY 1 MINVALUE 1 CACHE 20 NOCYCLE NOORDER;

CREATE TABLE HOSPITAL.PAT_ERX_AUTHORIZATION
(
ID		NUMBER NOT NULL,
REQ_ID	NUMBER NOT NULL,
AUTH_ID	NUMBER ,
IDPayer NVARCHAR2(255),
DenialCode NVARCHAR2(255),
Start_Date NVARCHAR2(255),
End_Date NVARCHAR2(20)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX PAT_ERX_AUTHORIZATION_PK ON PAT_ERX_AUTHORIZATION
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;

CREATE OR REPLACE TRIGGER PAT_ERX_AUTHORIZATION 
BEFORE INSERT
ON PAT_ERX_AUTHORIZATION 
REFERENCING NEW AS New OLD AS Old
FOR EACH ROW
DECLARE
tmpVar NUMBER;

BEGIN
   tmpVar := 0;

   SELECT PAT_ERX_AUTHORIZATION_SEQ.NEXTVAL INTO tmpVar FROM dual;
   :NEW.ID := tmpVar;

   EXCEPTION
     WHEN OTHERS THEN
       -- Consider logging the error and then re-raise
       RAISE;
END ;

ALTER TABLE PAT_ERX_AUTHORIZATION ADD (
  CONSTRAINT PAT_ERX_AUTHORIZATION_PK
 PRIMARY KEY
 (ID));
 